### ISSUE TITLE
vim E887: sorry this command is disabled, the python

### ISSUE THREAD

**Issue by chusiang** [vim-tw/ama#15]
在 macOS 10.11.6 使用 Homebrew 升級 Vim 至 8.0 時，搭配 YouCompleteMe (YCM) 可能會出現 `vim E887: sorry this command is disabled, the python ...` 的錯誤訊息。

**Comment by chusiang** [comment]
移除 macvim，並改用 Caskroom 底下的 macvim 重裝 ，別自己編可暫時獲得改善。

```
$ brew uninstall macvim
$ brew install Caskroom/cask/macvim
```

## Reference
- [Issue with pyenv and vim plugin: E887: Sorry, this command is disabled · Issue #234 · yyuu/pyenv](https://github.com/yyuu/pyenv/issues/234)

**Comment by chusiang** [comment]
當初 error 時忘了先截圖，可惜 …。

**Comment by tonkoshkurik** [comment]
the same after reinstall macvim
