### ISSUE TITLE
在 git commit 時出現 Vundle 的套件問題

### ISSUE THREAD

**Issue by wildskyf** [vim-tw/ama#2]
如附圖，想問有沒有人有遇過這樣的狀況，以及如何解決。
![2015-12-07 12-33-17](https://cloud.githubusercontent.com/assets/6042803/11619110/d6131fa8-9cde-11e5-8092-92ea0364850a.png)

> 我就是一個看到 warning 會不舒服的人…

**Comment by wildskyf** [comment]
ref: https://github.com/VundleVim/Vundle.vim/issues/675

**Comment by othree** [comment]
手動升級一下 Vundle

**Comment by othree** [comment]
```
cd .vim/bundle/vundle
git pull
```

**Comment by wildskyf** [comment]
我的是這個 https://github.com/VundleVim/Vundle.vim
剛剛更新過後還是一樣有問題

**Comment by othree** [comment]
Follow the readme ~~

```
call vundle#begin()
```

**Comment by wildskyf** [comment]
這個是我目前的設定檔，應該沒錯才對
https://github.com/wi1d5ky/myConfig/blob/master/.vimrc

**Comment by chusiang** [comment]
我目前在 Debian 8 底下補上 [molokai.vim](https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim) 這個 colorscheme 還有 ctags 後，再設個 vundle 都挺正常的喔！
- Debian 8 (docker)
- Vim 7.4.576

**Comment by wildskyf** [comment]
不好意思忘記提供了！

我的環境是這樣
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 20 2015 09:52:41)
Fedora 23

**Comment by chusiang** [comment]
1. `Cannot find color scheme 'molokai'` 是因為 Vim 在 ~/.vim/colors/ 底下找不到 molokai 這個 colorscheme。
   
   ```
   $ mkdir ~/.vim/colors
   $ cp ~/.vim/bundle/Molokai/colors/molokai.vim ~/.vim/colors/
   ```
2. 請附上您的 gitconfig。
   
   ```
   $ cat ~/.gitconfig
   ```

**Comment by wildskyf** [comment]
您一提到 git config 就讓我想起我好像沒有設定 editor
設定過後就沒有了！！！

預設可能是用 vi 所以不認得 vim 的東西
附上修改 editor 的指令：

`$ git config --global core.editor vim`

感謝 @chusiang ！

**Comment by chusiang** [comment]
@wi1d5ky 在 redhat, fedora, centos 的系統裡，裝好 vim 後是不會取代掉 vi 這個指令。在使用 git commit 時還是會代出 vi 來操作，但因為 vi 不支援寫給 vim 的 plugin 才會造成以上的問題。

解法除了指定 editor 給 git 外，還可以用 bash alias 或 path 來取代 vi。
1. bash alias.
   
   ```
   $ alias vi='vim'
   ```
2. path.
   
   ```
   $ ln -s /usr/bin/vim /usr/local/bin/vi
   ```

**Comment by wildskyf** [comment]
但我直接在 command line 輸入 vi 時打開的卻是 vim，我記得我好像也沒有做過類似的設定
感謝提供其他方法！！

**Comment by chusiang** [comment]
試試看在 console 裡輸入 `$ \vi`  看看。

```
[root@5d76d90bb044 sandbox]# \vi
Error detected while processing /root/.vimrc:
line   23:
E492: Not an editor command: Plugin 'VundleVim/Vundle.vim'
line   26:
E492: Not an editor command: Plugin 'Molokai'
line   27:
E492: Not an editor command: Plugin 'itchyny/lightline.vim'
line   28:
E492: Not an editor command: Plugin 'snipMate'
line   29:
E492: Not an editor command: Plugin 'mattn/emmet-vim'
line   30:
E492: Not an editor command: Plugin 'ap/vim-css-color'
line   31:
E492: Not an editor command: Plugin 'scrooloose/syntastic'
line   32:
E492: Not an editor command: Plugin 'vim-scripts/taglist.vim'
line   33:
E492: Not an editor command: Plugin 'scrooloose/nerdtree'
line   34:
E492: Not an editor command: Plugin 'xolox/vim-misc'
line   35:
E492: Not an editor command: Plugin 'xolox/vim-notes'
line   36:
E492: Not an editor command: Plugin 'cakebaker/scss-syntax.vim'
line  108:
E185: Cannot find color scheme 'molokai'
Press ENTER or type command to continue
```

**Comment by wildskyf** [comment]
看起來還是 Vim，不過就像我當時開這個 issue 一樣，出現一堆錯誤訊息。
![2015-12-08 14-08-22](https://cloud.githubusercontent.com/assets/6042803/11649026/2b60c04c-9db5-11e5-8428-94fac6d2fb42.png)

**Comment by chusiang** [comment]
vim 是有分 minimal 跟 enhanced 的，minimal 的話只有基本功能喔！

```
[root@5d76d90bb044 sandbox]# rpm -qa | grep vim
vim-minimal-7.4.827-1.fc23.x86_64
vim-common-7.4.827-1.fc23.x86_64
vim-filesystem-7.4.827-1.fc23.x86_64
vim-enhanced-7.4.827-1.fc23.x86_64
```

詳情請自己比對一下 `$ vi --version` 和  `$ vim --version` 了。

ps: 在下是使用 docker 建置測試環境的，一般不建議直接使用 root 操作系統。

**Comment by wildskyf** [comment]
感謝凍仁大大詳細的解說 <(_ _)> 

docker 我還沒學，之後有空再來學;P
