### ISSUE TITLE
Integration the Telegram and Github with GitHubBot

### ISSUE THREAD

**Issue by chusiang** [vim-tw/ama#3]
# GitHubBot
- https://telegram.me/GitHubBot
- Result
  ![2015-12-07-integration-the-telegram-and-github-with-githubbot](https://cloud.githubusercontent.com/assets/219066/11625398/b6ab2804-9d15-11e5-80e2-44124905f8e1.png)

**Comment by chusiang** [comment]
second test.

**Comment by chusiang** [comment]
感謝 Sean 提供 GitHubBot。

**Comment by Sea-n** [comment]
@chusiang What?!
