### ISSUE TITLE
自定快速鍵

### ISSUE THREAD

**Issue by Sea-n** [vim-tw/ama#9]
請問要怎麼作才能像 Ctrl P 這樣在輸入模式即可使用？

**Comment by chusiang** [comment]
不了解以上敘述，請補充。

**Comment by edentsai** [comment]
是想問 `imap` 自訂快速鍵在 Insert Mode 內使用嗎？
- `nmap`: Normal mapping
- `imap`: Insert mapping

**Comment by chusiang** [comment]
@Sea-n 請問該問題已得到解答了嗎？若完成那在下要關閉此 issue 了喔。
